# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               ▇ ▅ █ ▅ ▇ ▂ ▃ ▁ ▁ ▅ ▃ ▅ ▅ ▄ ▅ ▇
tagline:             'Knock, knock.'
description:         'random tech musings. By <a href="https://twitter.com/shivprasad" target="_blank">@shivprasad</a>.'
url:                 http://shivprasad.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Shivprasad Bade
  url:               https://twitter.com/shivprasad
  email:             shivprasad@gmail.com

# Custom vars
version:             1.0.0
